require_relative "validates_phone_number/version"
require_relative "validates_phone_number/message"
require_relative "validates_phone_number/formats"
require_relative "validates_phone_number/validator"
